service: dynamo-test

provider:
  name: aws
  runtime: python3.8
  stage: master
  region: us-east-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:Scan
    Resource: "arn:aws:dynamodb:us-east-2:798327857257:table/desempenoacademico"
custom:
  pythonRequirements:
    fileName: requirements.txt
    dockerizePip: true
    slim: true
    slimPatterns:
      - "*.dist-info"
  stageEnv: master

package:
  exclude:
    - package.json
    - package-lock.json
    - README.md
    - template.yml
    - Dockerfile
    - docker-compose.yml
    - funnel_example.json
    - rates.json
    - requirements*
    - manage.py
    - .gitignore
    - pytest.ini
    - .coverage
    - .coveragerc
    - .env.yml.example
    - .idea/**
    - node_modules/**
    - dynamodb_local_db/**
    - tests/**
    - .pytest_cache/**
    - __pycache__/**

functions:
  main:
    handler: handler.main
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: desempenoacademico
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline
